name: Build and deploy ASP.Net Core app to Azure Web App - cmr-rcjy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Install Node.js for the React build
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x" # or whatever version your React project uses

      # Install dependencies and build the React app
      - name: Build React front‑end
        working-directory: Frontend/my-app
        run: |
          npm install
          npm run build

      # Copy the React build into the API’s wwwroot folder
      - name: Copy React build to wwwroot
        run: |
          # Ensure the wwwroot folder exists
          New-Item -ItemType Directory -Force -Path Commander/wwwroot
          # Copy all files from the React build to wwwroot
          Copy-Item -Path Frontend/my-app/build/* -Destination Commander/wwwroot -Recurse -Force

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: dotnet build
        run: dotnet build --configuration Release

      # Publish includes the React files now present in wwwroot
      - name: dotnet publish
        run: dotnet publish -c Release -o '${{ env.DOTNET_ROOT }}/myapp'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_361518B30B144DD882109F150474FDF3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FC669A969D4148928C885A6A2DF20645 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6FC707AB03C945F0A236F697A614DABD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: cmr-rcjy
          slot-name: Production
          package: .
